### ISSUE TITLE
very weird results on IP2LOCATION_COUNTRY_SHORT logging/filtering - follow up

### ISSUE THREAD

**Issue by wienfuchs** [chrislim2888/IP2Location-Apache-Module#3]
following https://github.com/ip2location/ip2location-apache/issues/2 - I downloaded and installed latest master.zip from here (but left https://github.com/ip2location/IP2Location-C-Library/) and produced a similar weird [location.log](https://github.com/chrislim2888/IP2Location-Apache-Module/files/5627335/location.log)

**Comment by chrislim2888** [comment]
It might be an issue with large BIN file. Please try with the latest BIN which is optimized.
